### ISSUE TITLE
Contentful core package

### ISSUE THREAD

**Issue by stevejcox** [cmpsr/composer#37]
**User Story**
As a consumer of Composer, I may want to integrate with Contentful without having to use any of the Composer components, purely using the Contentful package as a way of consuming / mapping content models to components. I should be able to utilize `ContentfulContext` with a simple mapping of only the components i provide. There should be no reference to any additional components in the bundled JS packages.

**AC**
To split the Contentful package into `contentful/core` and `contentful/catalogue` where `core` handles the main functionality and `catalogue` handles the mapping between Composer Catalogue items and Contentful.

**Comment by ryanhefner** [comment]
@stevejcox Will wait to close this one out until the `contentful-catalog` package is in there and all squared away.
